/**
 * # Gitea OIDC
 *
 * Creates the necessary Zitadel resources (project, OIDC app, roles, user grants)
 * for Gitea to authenticate via Zitadel SSO.
 *
 * ## Deployment order
 *
 *   1. `tofu apply` - creates Zitadel project, app, roles, and grants
 *   2. Copy the `stack_env_guide` output values into `stack.env`
 *   3. `docker compose up` - starts Gitea; `gitea-init` registers the auth
 *      source automatically using the values from `stack.env`
 *
 * ## Role mapping (via the `flatRoles` Zitadel Action)
 *
 *   The existing `flatRoles` Action flattens Zitadel project roles into a
 *   plain `roles` array in the token, e.g. ["gitea_admin", "gitea_user"].
 *   Gitea reads this via --group-claim-name=roles and maps:
 *     gitea_admin  →  Gitea administrator
 *     gitea_user   →  regular Gitea user (default for any authenticated user)
 */

terraform {
  required_version = ">= 1.10.5"

  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = ">= 2.5.0"
    }
  }
}

locals {
  base_domain = "my.world"
}

provider "zitadel" {
  domain           = "zitadel.${local.base_domain}"
  insecure         = "false"
  port             = "443"
  jwt_profile_file = "${path.module}/../../admin_key.json"
}

module "gitea_web_ui_oidc" {
  source = "../../../common/modules/oidc"

  org_name         = "Sanctum"
  project_name     = "Gitea"
  application_name = "Gitea Web UI"
  app_type         = "OIDC_APP_TYPE_WEB"

  # POST method: Gitea sends client_secret in the request body during token
  # exchange. BASIC (HTTP Authorization header) is not supported by Gitea's
  # OAuth2 implementation.
  auth_method_type = "OIDC_AUTH_METHOD_TYPE_POST"

  # Gitea's OAuth2 callback path is /user/oauth2/<provider-name>/callback.
  # "Zitadel" here must match the --name passed to gitea admin auth add-oauth
  # in the gitea-init container (and the ZITADEL_PROVIDER_NAME in stack.env).
  redirect_uris             = ["https://gitea.${local.base_domain}/user/oauth2/Zitadel/callback"]
  post_logout_redirect_uris = ["https://gitea.${local.base_domain}/"]

  response_types = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types    = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"]

  access_token_type           = "OIDC_TOKEN_TYPE_BEARER"
  access_token_role_assertion = true
  id_token_role_assertion     = true
  id_token_userinfo_assertion = true

  project_roles = {
    "gitea_admin" = {
      display_name = "Gitea admin"
      group        = "gitea"
    }
    "gitea_user" = {
      display_name = "Gitea user"
      group        = "gitea"
    }
  }

  user_grants = {
    "igor" = {
      user_name = "igor.voronin@${local.base_domain}"
      role_keys = ["gitea_admin"]
    }
  }
}

# =============================================================================
# Outputs
# =============================================================================

# Everything you need to paste into stack.env before running docker compose up.
# Run: tofu output -raw stack_env_guide
output "stack_env_guide" {
  description = "Paste these values into stack.env, then run docker compose up"
  sensitive   = true
  value       = <<-EOT

    # --- Zitadel OIDC (generated by tofu apply) ------------------------------
    # Used by the gitea-init container to register Zitadel as an auth source.
    # The provider name MUST match the redirect URI registered in Zitadel above.
    ZITADEL_CLIENT_ID=${module.gitea_web_ui_oidc.client_id}
    ZITADEL_CLIENT_SECRET=${module.gitea_web_ui_oidc.client_secret}
    ZITADEL_DISCOVERY_URL=https://zitadel.${local.base_domain}/.well-known/openid-configuration
    ZITADEL_PROVIDER_NAME=Zitadel

    # --- Runner token (generate once, keep stable) ---------------------------
    # Set the same value in both places so Gitea accepts it on first boot and
    # the runner uses it to self-register. Generate with: openssl rand -hex 24
    # GITEA_RUNNER_REGISTRATION_TOKEN=<your value here>

  EOT
}

output "client_id" {
  description = "Zitadel client ID for Gitea"
  value       = module.gitea_web_ui_oidc.client_id
  sensitive   = true
}

output "client_secret" {
  description = "Zitadel client secret for Gitea"
  value       = module.gitea_web_ui_oidc.client_secret
  sensitive   = true
}

output "oidc_discovery_url" {
  description = "Zitadel OpenID Connect auto-discovery URL"
  value       = "https://zitadel.${local.base_domain}/.well-known/openid-configuration"
}
