{
 "title": "Containers",
 "tags": [
  "Alloy",
  "Docker",
  "Docker host"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Host CPU usage",
   "type": "gauge",
   "description": "Shows overall CPU usage as a percentage.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used memory (vs total memory)",
   "type": "gauge",
   "description": "Memory used by containers vs total memory available to the host.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_memory_bytes", "legendFormat": "__auto" },
    {
     "expr": "sum(container_memory_working_set_bytes{project!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker storage usage",
   "type": "gauge",
   "description": "Used space in <code>/var/lib/docker</code>. Includes volumes, images, container layers, and build cache.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/vdb\", mountpoint=\"/var/lib/docker\"} - node_filesystem_avail_bytes{device=\"/dev/vdb\", mountpoint=\"/var/lib/docker\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/vdb\",mountpoint=\"/var/lib/docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available host memory",
   "type": "gauge",
   "description": "Memory available on the host vs total memory on the host.",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "stat",
   "description": "Network bandwidth usage (RX/TX) for primary interface. Shows incoming and outgoing traffic in bytes per second.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__range]) * 100",
     "legendFormat": "Receive/Download - RX ({{device}})"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[$__range])",
     "legendFormat": "Transmit / Upload - TX ({{device}})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Container CPU Distribution",
   "type": "piechart",
   "description": "Shows which containers are using CPU relative to each other.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{project!=\"\"}[5m])",
     "legendFormat": "{{name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "description": "CPU usage per container in cores (logarithmic scale). Shows resource consumption relative to total available CPU.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{project!=\"\"}[1m])",
     "legendFormat": "{{name}} ({{service}})"
    },
    {
     "expr": "count(count by (cpu) (node_cpu_seconds_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Used memory",
   "type": "piechart",
   "description": "Memory used by the Docker containers in relation to each other.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{project!=\"\"}",
     "legendFormat": "{{name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Memory usage over time",
   "type": "timeseries",
   "description": "Memory used vs available memory over time period",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{project!=\"\"}",
     "legendFormat": "{{name}} ({{service}})"
    },
    {
     "expr": "engine_daemon_engine_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Containers using disk space",
   "type": "timeseries",
   "description": "Shows which containers use how much disk space.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{project!=\"\"}",
     "legendFormat": "{{name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Disk throughput",
   "type": "timeseries",
   "description": "Shows read/write speeds in MB/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"vdb\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"vdb\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"vdb\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"vdb\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "description": "Network bandwidth usage (RX/TX) for primary interface. Shows incoming and outgoing traffic in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Receive/Download - RX ({{device}})"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "Transmit / Upload - TX ({{device}})"
    }
   ]
  }
 ]
}