{
 "title": "Container logs",
 "description": "Searchable container logs",
 "tags": [
  "Loki",
  "Docker",
  "Docker host"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "log_level",
    "label": "Current log level",
    "query": "All : .*,\nErrors : (err.*|fail.*),\nWarnings : (warn.*),\nInfo : info,\nDebug : debug,\nTrace : trace"
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {container_name=~\"${containers}\", container_name!=\"\", container_name!=\"loki\"} # ignoring loki errors\n    | pattern `<timestamp> <level> <message>` \n    | level =~ `(?i)(err.*|fail.*)`\n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Logs / s / container",
   "type": "timeseries",
   "description": "Logs per time unit per container",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (container_name) (\n  count_over_time(\n    {container_name=~\"${containers}\", container_name!=\"\"} \n    | pattern `<timestamp> <level> <message>` \n    | level =~ `(?i)(${log_level:pipe})` \n    [$__auto]\n  )\n)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {container_name=~\"${containers}\", container_name!=\"\"} \n    | pattern `<timestamp> <level> <message>` \n    | level =~ `(?i)(warn.*)` \n    [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_project!=\"\"} | pattern `<timestamp> <level> <message>` | container_name =~ `(i?)${containers}` | level =~ `(i?)${log_level:pipe}` | line_format \"{{.compose_service}} | {{.level}} | {{.message}}\"",
     "legendFormat": "{{compose_service}}"
    }
   ]
  }
 ]
}